export const PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "ALL_PRODUCT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
